<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'Uusia päivityksiä ei voida tarkistaa, koska \'allow_url_fopen\' ei ole sallittu järjestelmässä.',
'Upgrade check failed message'		=>	'Uusien päivityksien tarkistus epäonnistui tuntemattomasta syystä.',
'Running latest version message'	=>	'Sinulla on käytössä viimeisin versio FluxBB:stä.',
'New version available message'		=>	'Uusi versio FluxBB:stä on saatavilla. Voit ladata uusimman version osoitteesta %s.',
'Deleted install.php redirect'		=>	'Tiedoston poisto onnistui. Uudelleenohjataan…',
'Delete install.php failed'			=>	'install.php-tiedoston poistaminen epäonnistui. Poista tiedosto manuaalisesti.',
'Not available'						=>	'Ei saatavilla',
'Forum admin head'					=>	'Keskustelualueen ylläpito',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'Tervetuloa FluxBB:n ylläpitoon. Riippuen siitä oletko ylläpitäjä vai moderaattori voit:',
'Welcome 1'							=>	'Muuttaa kategorioiden ja alueiden järjestystä.',
'Welcome 2'							=>	'Muuttaa alueiden asetuksia.',
'Welcome 3'							=>	'Hallita käyttäjien ja vieraiden oikeuksia.',
'Welcome 4'							=>	'Katsoa käyttäjien käyttämiä IP-osoitteita.',
'Welcome 5'							=>	'Antaa käyttäjille porttikieltoja.',
'Welcome 6'							=>	'Sensuroida sanoja.',
'Welcome 7'							=>	'Luoda käyttäjäryhmiä ja ylentää käyttäjiä.',
'Welcome 8'							=>	'Karsia vanhoja viestejä.',
'Welcome 9'							=>	'Käsitellä ilmiantoja.',
'Alerts head'						=>	'Varoitukset',
'Install file exists'				=>	'install.php-tiedosto on vielä olemassa ja se tulisi poistaa. %s.',
'Delete install file'				=>	'Poista tiedosto',
'About head'						=>	'Tietoja FluxBB:stä',
'FluxBB version label'				=>	'FluxBB:n versio',
'Check for upgrade'					=>	'Tarkista päivitykset',
'FluxBB version data'				=>	'v%s - %s',
'Server statistics label'			=>	'Palvelimen tilastot',
'View server statistics'			=>	'Katso palvelimen tilastoja',
'Support label'						=>	'Tuki',
'Forum label'						=>	'Alue',
'IRC label'							=>	'IRC-kanava',

// Language definitions used in admin_statistics.php
'PHPinfo disabled message'			=>	'PHP-funktion phpinfo() käyttö on estetty tällä palvelimella.',
'Server statistics head'			=>	'Palvelimen tilastot',
'Server load label'					=>	'Palvelimen kuorma',
'Server load data'					=>	'%s - %s käyttäjää paikalla',
'Environment label'					=>	'Ympäristö',
'Environment data OS'				=>	'Käyttöjärjestelmä: %s',
'Show info'							=>	'Näytä tietoja',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Accelerator: %s',
'Turck MMCache'						=>	'Turck MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net/',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer/',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Tietokanta',
'Database data rows'				=>	'Riviä: %s',
'Database data size'				=>	'Koko: %s',
);
