<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'Käyttäjätunnuksella rekisteröitynyttä käyttäjää ei löytynyt. Jos haluat antaa porttikierron, joka ei ole sidottu tiettyyn käyttäjätunnukseen, jätä käyttäjätunnus tyhjäksi.',
'No user ID message'		=>	'ID-numerolla ei löydy rekisteröityneitä käyttäjiä.',
'User is admin message'		=>	'Käyttäjä %s on ylläpitäjä eikä sille voi antaa porttikieltoa. Jos haluat antaa ylläpitäjälle porttikiellon, sinun tulee alentaa hänet.',
'User is mod message'		=>	'Käyttäjä %s on moderaattori eikä sille voi antaa porttikieltoa. Jos haluat antaa moderaattorille porttikiellon, sinun tulee alentaa hänet.',
'Must enter message'		=>	'Anna vähintään käyttäjätunnus, IP-osoite tai sähköpostiosoite.',
'Cannot ban guest message'	=>	'Vieraalle ei voi antaa porttikieltoa.',
'Invalid IP message'		=>	'Antamasi IP-osoite tai IP-osoitealue on virheellinen.',
'Invalid e-mail message'	=>	'Antamasi sähköpostiosoite (esim. etunimi.sukunimi@domain.com) tai osa siitä (esim domain.com) on virheellinen.',
'Invalid date message'		=>	'Annoit virheellisen loppumispäivämäärän.',
'Invalid date reasons'		=>	'Päivämäärä tulee olla muotoa YYYY-MM-DD ja annetun päivämäärän tulee olla vähintään yhden päivän verran tulevaisuudessa.',
'Ban added redirect'		=>	'Porttikielto lisätty. Uudelleenohjataan…' ,
'Ban edited redirect'		=>	'Porttikieltoa muutettu. Uudelleenohjataan…',
'Ban removed redirect'		=>	'Porttikielto poistettu. Uudelleenohjataan…',

'New ban head'				=>	'Uusi porttikielto',
'Add ban subhead'			=>	'Lisää porttikielto',
'Username label'			=>	'Käyttäjätunnus',
'Username help'				=>	'Porttikielto käyttäjätunnukselle (case-insensitive).',
'Username advanced help'	=>	'Porttikielto käyttäjätunnukselle (case-insensitive). Seuraavalla sivulla voit määrittää IP- tai sähköpostiosoitteen. Jos haluat antaa porttikiellon tietylle IP-osoitteelle tai -osoitealueelle, jätä sähköpostiosoite tyhjäksi.',

'Ban search head'			=>	'Hae porttikieltoja',
'Ban search subhead'		=>	'Anna hakukriteerit',
'Ban search info'			=>	'Haetaan porttikieltoja tietokannasta. Voit antaa yhden tai useamman hakutermin, jolla haetaan. * merkit jokerimerkkeinä on sallittuja. Jos haluat tarkastella kaikkia porttikieltoja, jätä kaikki kentät tyhjäksi.',
'Date help'					=>	'(yyyy-mm-dd)',
'Message label'				=>	'Viesti',
'Expire after label'		=>	'Loppuu jälkeen',
'Expire before label'		=>	'Loppuu ennen',
'Order by label'			=>	'Järjestä',
'Order by username'			=>	'Käyttäjätunnus',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'Sähköposti',
'Order by expire'			=>	'Loppumispäivämäärä',
'Ascending'					=>	'Nouseva',
'Descending'				=>	'Laskeva',
'Submit search'				=>	'Hae',

'E-mail label'				=>	'Sähköposti',
'E-mail help'				=>	'Sähköpostiosoite tai sähköpostiosoitteen domain, jolle haluat antaa porttikiellon (esimerkiksi someone@somewhere.com tai somewhere.com). Katso "Salli sähköpostiosoitteet, joilla porttikielto" Oikeudet-sivulta lukeaksesi lisää.',
'IP label'					=>	'IP-osoite tai -alue',
'IP help'					=>	'IP-osoite tai -alue, jolle haluat antaa porttikiellon (esimerkiksi 150.11.110.1 tai 150.11.110). Erottele osoitteet välilyönnillä. Jos IP-osoite on jo annettu se on viimeisin IP-osoite, jota käyttäjä on käyttänyt.',
'IP help link'				=>	'Klikkaa %s nähdäksesi käytetyt IP-osoitteet tälle käyttäjälle.',
'Ban advanced head'			=>	'Tarkemmat porttikieltoasetukset',
'Ban advanced subhead'		=>	'Täydennä porttikieltoa IP-osoitteella ja sähköpostiosoitteella',
'Ban message label'			=>	'Porttikiellon viesti',
'Ban message help'			=>	'Viesti tullaan näyttämään, kun porttikiellon saanut käyttäjä saapuu keskustelualueelle.',
'Message expiry subhead'	=>	'Porttikiellon viesti ja päättymisaika',
'Ban IP range info'			=>	'Ole varovainen antaessasi porttikiellon IP-alueelle, koska joku muukin käyttäjä saattaa joutua porttikieltolistalle.',
'Expire date label'			=>	'Päättymispäivämäärä',
'Expire date help'			=>	'Päivämäärä milloin porttikielto päättyy automaattisesti (muodossa: yyyy-mm-dd). Jätä tyhjäksi, jos porttikielto poistetaan käsin.',

'Results head'				=>	'Hakutulokset',
'Results username head'		=>	'Käyttäjätunnus',
'Results e-mail head'		=>	'Sähköposti',
'Results IP address head'	=>	'IP-osoite tai -alue',
'Results expire head'		=>	'Päättyy',
'Results message head'		=>	'Viesti',
'Results banned by head'	=>	'Porttikiellon antaja',
'Results actions head'		=>	'Toiminnot',
'No match'					=>	'Ei osumia',
'Unknown'					=>	'Tuntematon',

);
