<?php

// Language definitions used in admin_maintenance.php
$lang_admin_maintenance = array(

'Maintenance head'				=>	'Keskustelue on huoltotilassa',
'Rebuild index subhead'			=>	'Luo hakuindeksi uudelleen',
'Rebuild index info'			=>	'Jos olet lisännyt, muokannut tai poistanut manuaalisesti viestejä tietokannasta tai jos hakujen kanssa on ongelmia, kannattaa hakuindeksi luoda uudelleen. Parhaan suorituskyvyn saa, kun laittaa keskustelualueen %s hakuindeksien uudelleen luomisen ajaksi. <strong>Hakuindeksin uudelleen luominen voi kestää kauan ja saattaa lisätä CPU-kuormaa prosessin aikana!</strong>',
'Posts per cycle label'			=>	'Viestiä per kierros',
'Posts per cycle help'			=>	'Viestien määrä, joka käsitellään per sivunlataus. Esimerkiksi jos annat arvoksi 300, kolmesataa veistieä tullaan käsittelemään kerrallaan, jonka jälkeen sivu ladataan uudelleen. Tällä varmistetaan, ettei palvelin aikakatkaise yhteyttä kesken hakuindeksien luomisen.',
'Starting post label'			=>	'Aloitetaan viestistä ID',
'Starting post help'			=>	'Viestin ID-numero, mistä hakuindeksin luominen aloitetaan. Oletusarvo on ensimmäinen tietokannassa oleva ID-numero. Normaalitilanteessa tätä ei tarvitse muuttaa.',
'Empty index label'				=>	'Tyhjennä indeksi',
'Empty index help'				=>	'Valitse tämä, jos haluat, että hakuindeksi tyhjennetään ennen luomista.',
'Rebuild completed info'		=>	'Kun käsittely on saatu loppuun, sinut uudelleenohjataan takaisin tälle sivulle. On suotavaa, että sallit Javascript-komentojen suorittamisen hakuindeksin luomisen ajaksi. Jos sinun täytyy keskeyttää viestien käsittely, pistä ylös viimeksi käsitellyn viestin ID-numero ja anna tämä ID + 1 "Aloitetaan viestistä ID"-kenttään, jos haluat jatkaa uudelleen käsittelyä siitä kohdasta missä se keskeytyi.',
'Rebuild index'					=>	'Luo indeksi',
'Rebuilding search index'		=>	'Luo hakuindeksiä',
'Rebuilding index info'			=>	'Luodaan indeksiä. Nyt voisi olla hyvä aika käydä hakemassa kuppi kahvia :-)',
'Processing post'				=>	'Käsitellään viestiä <strong>%s</strong> …',
'Click here'					=>	'Klikkaa tästä',
'Javascript redirect failed'	=>	'Javascript uudelleenohjaus epäonnistui. %s jatkaaksesi…',
'Posts must be integer message'	=>	'Viestiä per kierros tulee antaa positiivisena kokonaislukuna.',
'Days must be integer message'	=>	'Days to prune tulee olla positiivinen kokonaisluku.',
'No old topics message'			=>	'Aiheita, jotka olisivat %s päivää vanhoja ei löydy. Vähennä "Päivää vanha" arvoa ja kokeile uudelleen.',
'Posts pruned redirect'			=>	'Viestejä karsittu. Uudelleenohjataan…',
'Prune head'					=>	'Karsi',
'Prune subhead'					=>	'Karsi vanhat viestit',
'Days old label'				=>	'Päivää vanha',
'Days old help'					=>	'The number of days "old" a topic must be to be pruned. E.g. if you were to enter 30, every topic that didn\'t contain a post dated less than 30 days old would be deleted.',
'Prune sticky label'			=>	'Poista nostetut aiheet',
'Prune sticky help'				=>	'Kun tämä on valittu, myös nostetut aiheet tullaan poistamaan.',
'Prune from label'				=>	'Poista alueelta',
'All forums'					=>	'Kaikilta alueilta',
'Prune from help'				=>	'Alue, jolta haluat poistaa vanhat viestit.',
'Prune info'					=>	'Käytä tätä ominaisuutta varoen. <strong>Poistettuja viestejä ei voi palauttaa.</strong> Parhaan suorituskyvyn saavuttamiseksi keskustelualue kannattaa laittaa %s viestien poistamisen ajaksi.',
'Confirm prune subhead'			=>	'Varmista viestien poisto',
'Confirm prune info'			=>	'Oletko varma, että haluat poistaa kaikki aiheet, jotka ovat vanhempia kuin %s päivää lähtien %s (%s aihetta).',
'Confirm prune warn'			=>	'Varoitus! Viestit tullaan poistamaan pysyvästi.',

);
