<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Profiili',
'Section essentials'			=>	'Käyttäjätiedot',
'Section personal'				=>	'Päätiedot',
'Section messaging'				=>	'Viestivälineet',
'Section personality'			=>	'Personointi',
'Section display'				=>	'Ulkoasu',
'Section privacy'				=>	'Yksityisyys',
'Section admin'					=>	'Administration',

// Miscellaneous
'Username and pass legend'		=>	'Anna käyttäjätunnuksesi ja salasana',
'Personal details legend'		=>	'Anna omat tietosi',
'Contact details legend'		=>	'Anna yhteystietosi',
'User activity'					=>	'Aktiivisuus',
'Paginate info'					=>	'Montako aihetta ja viestiä haluat nähdä yhdellä sivulla.',

// Password stuff
'Pass key bad'					=>	'Antamasi aktivointiavain on virheellinen tai umpeutunut. Pyydä uuden salasanan lähettämistä uudelleen. Jos tämä epäonnistuu, ota yhteyttä ylläpitoon osoitteeseen',
'Pass updated'					=>	'Salasanasi on päivitetty. Nyt voit kirjautua uudella salasanallasi.',
'Pass updated redirect'			=>	'Salasana päivitetty. Uudelleenohjataan…',
'Wrong pass'					=>	'Väärä salasana.',
'Change pass'					=>	'Vaihda salasana',
'Change pass legend'			=>	'Anna ja vahvista uusi salasanasi',
'Old pass'						=>	'Vanha salasana',
'New pass'						=>	'Uusi salasana',
'Confirm new pass'				=>	'Vahvista uusi salasana',
'Pass info'						=>	'Salasanojen tulee olla vähintään kuusi merkkiä pitkiä. Salasanoissa kirjainkoko merkitsee.',

// Email stuff
'Email key bad'					=>	'Sähköpostin aktivointiavain oli virheellinen tai vanhentunut. Pyydä sähköpostin uudelleen lähettämistä. Jos tämä epäonnistuu, ota yhteyttä ylläpitoon osoitteeseen',
'Email updated'					=>	'Sähköpostiosoite päivitetty.',
'Activate email sent'			=>	'Sähköposti on lähetetty annettuun osoitteeseen. Viestissä on ohjeet kuinka aktivoida uusi sähköpostiosoite. Jos et saa viestiä, ota yhteyttä ylläpitoon osoitteeseen',
'Email legend'					=>	'Anna uusi sähköpostiosoite',
'Email instructions'			=>	'Sähköposti on lähetetty uuteen sähköpostiosoitteeseen aktivointi linkin kanssa. Sinun tulee klikata sähköpostissa olevaa linkkiä aktivoidaksesi uuden sähköpostiosoitteen.',
'Change email'					=>	'Vaihda sähköpostiosoite',
'New email'						=>	'Uusi sähköpostiosoite',

// Avatar upload stuff
'Avatars disabled'				=>	'Ylläpitäjä on estänyt avatarien käytön.',
'Too large ini'					=>	'Valittu tiedosto on liian iso ladattavaksi.',
'Partial upload'				=>	'Valittua tiedostoa ei voitu ladata. Yritä lataamista uudelleen.',
'No tmp directory'				=>	'Ladattua tiedostoa ei voitu tallentaa palvelimelle.',
'No file'						=>	'Et valinnut tiedostoa, jonka haluat ladata.',
'Bad type'						=>	'Ladatun tiedoston tyyppi ei ole sallittujen joukossa. Sallitut tiedostotyypit ovat gif, jpeg ja png.',
'Too wide or high'				=>	'Ladatun kuvan leveys ja / tai korkeus oli yli sallitun.',
'Too large'						=>	'Ladattu tiedosto oli yli sallitun rajan.',
'pixels'						=>	'pikseliä',
'bytes'							=>	'tavua',
'Move failed'					=>	'Palvelin ei pystynyt tallentamaan ladattua tiedostoa. Ota yhteyttä ylläpitoon osoitteeseen',
'Unknown failure'				=>	'Tapahtui tunnistamaton virhe. Yritä uudelleen.',
'Avatar upload redirect'		=>	'Avatar ladattu. Uudelleenohjataan…',
'Avatar deleted redirect'		=>	'Avatar poistettu. Uudelleenohjataan…',
'Avatar desc'					=>	'Avatar on kuva, joka näytetään käyttäjätunnuksesi alla jokaisessa viestissä. Se ei voi olla suurempi kuin',
'Upload avatar'					=>	'Lataa avatar',
'Upload avatar legend'			=>	'Anna ladattava avatar kuvatiedosto',
'Delete avatar'					=>	'Poista avatar', // only for admins
'File'							=>	'Tiedosto',
'Upload'						=>	'Lataa', // submit button

// Form validation stuff
'Forbidden title'				=>	'Otsikko, jonka kirjoitit, sisältää kiellettyjä sanoja. Sinun tulee valita toinen otsikko.',
'Profile redirect'				=>	'Käyttäjätiedot päivitetty. Uudelleenohjataan…',

// Profile display stuff
'Users profile'					=>	'%sn profiili',
'Username info'					=>	'Käyttäjätunnus: %s',
'Email info'					=>	'Sähköposti: %s',
'Posts info'					=>	'Viestit: %s',
'Registered info'				=>	'Rekisteröitynyt: %s',
'Last post info'				=>	'Viimeisin viesti: %s',
'Last visit info'				=>	'Viimeisin käynti: %s',
'Show posts'					=>	'Näytä kaikki viestit',
'Show topics'					=>	'Näytä kaikki aiheet',
'Show subscriptions'			=>	'Näytä kaikki seuraamiset',
'Realname'						=>	'Oikea nimi',
'Location'						=>	'Paikkakunta',
'Website'						=>	'Kotisivut',
'Invalid website URL'			=>	'Annettu sivun osoite on virheellinen.',
'Website not allowed'			=>	'Sinulla ei ole oikeutta lisätä kotisivua profiiliin vielä.',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'Microsoft-tili',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Allekirjoitus',
'Sig max size'					=>	'Maksimi pituus: %s merkkiä / rivien määrä: %s',
'Avatar legend'					=>	'Avatarin näyttöasetukset',
'Avatar info'					=>	'Avatar on kuva, joka näytetään viestiesi yhteydessä. Voit lisätä avatarin klikkaamalla alla olevaa linkkiä.',
'Change avatar'					=>	'Vaihda avatar',
'Signature legend'				=>	'Tallenna allekirjoituksesi',
'Signature info'				=>	'Allekirjoitus on lyhyt teksti, joka liitetään viestiesi alle. Voit kertoa allekirjoituksessa mitä tahansa itsestäsi. Jos BBCode-tagit on sallittuja niin voit käyttää niitä.',
'Sig preview'					=>	'Tämän hetkisen allekirjoituksen esikatselu:',
'No sig'						=>	'Ei tallennettua allekirjoitusta.',
'Signature quote/code/list/h'	=>	'quote-, code-, list- ja heading- BBCode-tagit ovat sallittuja allekirjoituksessa.',
'Topics per page'				=>	'Aiheet',
'Posts per page'				=>	'Viestit',
'Leave blank'					=>	'Jätä tyhjäksi, jos haluat käyttää keskustelualueen oletusta.',
'Subscription legend'			=>	'Muuta seuraamisasetuksia',
'Notify full'					=>	'Sisällytä tekstiversiot viesteistä ilmoitussähköposteihin.',
'Auto notify full'				=>	'Automaattisesti lisää seurattavaksi aiheet, jotka aloitat.',
'Show smilies'					=>	'Näytä hymiöt kuvioina.',
'Show images'					=>	'Näytä kuvat viesteissä.',
'Show images sigs'				=>	'Näytä kuvat käyttäjien allekirjoituksissa.',
'Show avatars'					=>	'Näytä käyttäjien avatarit viesteissä.',
'Show sigs'						=>	'Näytä käyttäjän allekirjoitus.',
'Style legend'					=>	'Valitsi haluamasi tyyli',
'Styles'						=>	'Tyylit',
'Admin note'					=>	'Ylläpitäjän muistiinpanot',
'Pagination legend'				=>	'Anna sivuutusasetukset',
'Post display legend'			=>	'Aseta viestien lukuasetukset',
'Post display info'				=>	'Jos käytät hidasta yhteyttä, poistamalla kuvien näyttämisen viesteissä ja allekirjoituksissa auttaa lataamaan sivut nopeammin.',
'Instructions'					=>	'Kun olet päivittänyt profiilisi, sinut uudelleenohjataan tälle sivulle.',

// Administration stuff
'Group membership legend'		=>	'Valitse käyttäjäryhmä',
'Save'							=>	'Tallenna',
'Set mods legend'				=>	'Anna moderaattorioikeudet',
'Moderator in info'				=>	'Valitse millä aluiella käyttäjällä on oikeudet moderoida viestejä. Huom: Tämä vaikuttaa vain moderaattoreihin. Ylläpitäjillä on täydet oikeudet kaikille alueille.',
'Update forums'					=>	'Päivitä alueet',
'Delete ban legend'				=>	'Poista käyttäjä (vain ylläpitäjät) tai anna porttikielto',
'Delete user'					=>	'Poista käyttäjä',
'Ban user'						=>	'Anna porttikielto',
'Confirm delete legend'			=>	'Tärkeää: Lue ennen käyttäjän poistamista',
'Confirm delete user'			=>	'Varmista käyttäjän poistaminen',
'Confirmation info'				=>	'Vahvista, että haluat poistaa käyttäjän', // the username will be appended to this string
'Delete warning'				=>	'Varoitus! Poistetuttuja käyttäjiä ja / tai viestejä ei voi palauttaa myöhemmin. Jos et halua poistaa tämän käyttäjän viestejä, viestit pitää poistaa manuaalisesti myöhemmin.',
'Delete posts'					=>	'Poista kaikki viestit ja aiheet, jotka käyttäjä on kirjoittanut.',
'Delete'						=>	'Poista', // submit button (confirm user delete)
'User delete redirect'			=>	'Käyttäjä poistettu. Uudelleenohjataan…',
'User promote redirect'			=>	'Käyttäjä ylennetty. Uudelleenohjataan…',
'Group membership redirect'		=>	'Käyttäjä lisätty ryhmään. Uudelleenohjataan…',
'Update forums redirect'		=>	'Alueen moderaattorioikeudet päivitetty. Uudelleenohjataan…',
'Ban redirect'					=>	'Uudelleenohjataan…',
'No delete admin message'		=>	'Ylläpitäjiä ei voi poistaa. Jos haluat poistaa käyttäjän, sinun tulee siirtää hänet toiseen käyttäjäryhmään.',

);
