<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Käyttäjähaku',
'No search permission'				=>	'SInulla ei ole oikeuksia käyttää hakutoimintoa.',
'Search flood'						=>	'Hakujen välissä tulee olla vähintään %s sekuntia. Odota %s sekuntia ennen kuin haet seuraavan kerran.',
'Search'							=>	'Hae',
'Search criteria legend'			=>	'Anna hakukriteerit',
'Search info'						=>	'Anna hakusana tai sanat, joilla haluat etsiä viestejä. Erottele hakutermit välilyönnein. Käytä AND, OR ja NOT operaattoreita parantaaksesi hakua. Anna kirjoittajan käyttäjätunnus, jos haluat hakea kirjoittajan mukaan. Voit käyttää myös * jokerimerkkinä.',
'Keyword search'					=>	'Haku sanan mukaan',
'Author search'						=>	'Haku kirjoittajan mukaan',
'Search in legend'					=>	'Valitse mistä etsit',
'Search in info'					=>	'Valitse miltä alueelta haluat etsiä.',
'Search multiple forums info'		=>	'Jos alueita ei ole valittu, haetaan kaikilta alueilta.',
'Forum search'						=>	'Alue',
'Search in'							=>	'Hae',
'Message and subject'				=>	'Viestitekstistä tai aiheen otsikoista',
'Message only'						=>	'Ainoastaan viestitekstistä',
'Topic only'						=>	'Ainoastaan otsikoista',
'Sort by'							=>	'Listaa',
'Sort order'						=>	'Listausjärjestys',
'Search results legend'				=>	'Valitse kuinka haluat nähdä hakutulokset',
'Search results info'				=>	'Voit valita miten haluat järjestellä ja katsoa hakutuloksia.',
'Sort by post time'					=>	'Kirjoitusajan mukaan',
'Sort by author'					=>	'Kirjoittajan mukaan',
'Sort by subject'					=>	'Otsikon mukaan',
'Sort by forum'						=>	'Aiheen mukaan',
'Ascending'							=>	'Nouseva',
'Descending'						=>	'Laskeva',
'Show as'							=>	'Näytä tulokset',
'Show as topics'					=>	'Aiheet',
'Show as posts'						=>	'Viestit',

// Results
'Search'							=>	'Hae',
'Search results'					=>	'Hakutulokset',
'Quick search show_new'				=>	'Uusi',
'Quick search show_recent'			=>	'Aktiivisista',
'Quick search show_unanswered'		=>	'Vastaamattomista',
'Quick search show_replies'			=>	'Vastatuista',
'Quick search show_user_topics'		=>	'Aiheet kirjoittanut %s',
'Quick search show_user_posts'		=>	'Viestit kirjoittanut %s',
'Quick search show_subscriptions'	=>	'Seuraajan %s',
'By keywords show as topics'		=>	'Aiheiden viestit, jotka sisältävät \'%s\'',
'By keywords show as posts'			=>	'Viestit, jotka sisältävät \'%s\'',
'By user show as topics'			=>	'Aiheet aloittanut %s',
'By user show as posts'				=>	'Viestit kirjoittanut %s',
'By both show as topics'			=>	'Aiheet, joiden viestit sisältävät \'%s\' %s kirjoittamana',
'By both show as posts'				=>	'Viestit, jotka sisältävät \'%s\' %s kirjoittamana',
'No terms'							=>	'Sinun tulee antaa vähintään yksi hakusana ja/tai kirjoittajan käyttäjätunnus, millä haluat etsiä viestejä.',
'No hits'							=>	'Ei hakutuloksia.',
'No user posts'						=>	'Haettu käyttäjätunnus ei ole kirjoittanut viestejä tälle keskustelualueelle.',
'No user topics'					=>	'Haettu käyttäjätunnus ei ole aloittanut aiheita tällä keskustelualueella.',
'No subscriptions'					=>	'Käyttäjä ei seuraa yhtään aihetta.',
'No new posts'						=>	'Viime käyntisi jälkeen ei ole kirjoitettu uusia viestejä.',
'No recent posts'					=>	'Viimeisen 24 tunnin aikana ei ole kirjoitettu uusia viestejä.',
'No unanswered'						=>	'Keskustelualueella ei ole viestejä ilman vastausta.',
'Go to post'						=>	'Siirry viestiin',
'Go to topic'						=>	'Siirry aiheeseen'

);
